server:
  port: 9101
spring:
  application:
    name: myshop-user
  datasource:
    url: jdbc:mysql://192.168.137.131:3306/springcloud?characterEncoding=UTF8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true
    generate-ddl: true
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
eureka:
  client:
    register-with-eureka: true # ??????????Eureka
    fetch-registry: true  # ????????Eureka??????
    service-url: # ???????
      defaultZone: http://localhost:8888/eureka
  instance:
    # ????????IP?????Eureka??????????true
    prefer-ip-address: true
